name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Assign runnable permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Set Version
        run: echo "::set-output name=version::$(echo ${{ github.sha }} | cut -c -6)"
        id: version

      - name: Set Release Name
        run: echo "::set-output name=release_name::$(echo ${{ github.sha }} | cut -c -6)"
        id: release_name

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.version.outputs.release_name }}
          tag_name: ${{ steps.version.outputs.version }}
          files: build/libs/chasing-tails.jar